version: "3"
services:
    my-docker-app:
        image: express_server
        ports:
        - "5000:5000"
        networks:
        - mern-app
        volumes:
        - .:/app
        - /app/node_modules
        depends_on:
        - mongo
    mongo:
        image: mongo:3.6.19-xenial
        ports:
        - "27017:27017"
        networks:
        - mern-app
networks:
    mern-app:
        driver: bridge
